#name SimpleCalc


INT 	:= "(0-9)+"
REAL 	:= "(0-9)*.(0-9)+"

PLUS 	:= "\+"
POWER	:= "\*\*"
MUL 	:= "\*"
DIV		:= "/"
SUB		:= "\-"
ASSIGN 	:= "="
LPAREN 	:= "\("
RPAREN 	:= "\)"
COMMENT := "//"	{
	token.literal = "";
	while (input->peek() != '\n')
	{
		token.literal += input->popLetter();
	}
	return true;
}

ID 		:= "(a-z|A-Z|_)(a-z|A-Z|_|0-9)*"


num		:= INT | REAL;
exp 	:= num MUL term | num DIV term | LPAREN exp RPAREN;
term	:= num PLUS exp | num SUB exp | num POWER exp | num;