#name SimpleCalc;

INT 	:= "(0-9)+";
REAL 	:= "(0-9)*.(0-9)+";

PLUS 	:= "\\+";
POWER	:= "\\*\\*";
MUL 	:= "\\*";
DIV		:= "/";
SUB		:= "\\-";
ASSIGN 	:= "=";
LPAREN 	:= "\\(";
RPAREN 	:= "\\)";
COMMENT := "//"	
	{
		token.literal = "";
		while (input->peek() != '\n')
		{
			token.literal += input->popLetter();
		}
		return true;
	};

ID 		:= "(a-z|A-Z|_)(a-z|A-Z|_|0-9)*";


num		:= INT | REAL;
factor 	:= num | LPAREN expr RPAREN;
term 	:= factor MUL term | factor DIV term | factor;
expr 	:= term PLUS expr | term SUB expr | term;

_start_ := expr;